name: A workflow to build and deploy my homepage
on: 
  push:
    branches:
      - master


jobs:
  build:
    name: Build homepage with Parcel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build